### PR TITLE
fix check for engine not for version IE

### PR DESCRIPTION
**Pull request by tfugmann**
Internet Explorer 11 is released, yay.  Microsoft changed the User-Agent string, browser check failed -> null pointer. 

This fix should enable the IE 11 support for unify and solve the problem by checking for the engine version not for the browser version.

### CODE REVIEW

**Comment by mcdit** [comment]
Awesome

**Comment by fastner** [comment]
I think this is not enough to get version of IE. You should do something like (MSIE|Trident) to don't destroy old versions. For new one this is okay.

**Comment by tfugmann** [comment]
It won't destroy the old versions,It's just a replacement for the IE9 or higher check. 
The "Trident"- string exists since 8 and the MSIE string isn't used anymore. 
So it seemed to make sense to check for the version of the engine.

**Comment by fastner** [comment]
Ah okay, I have not seen that you use trident version (6) instead of IE version (9).

**Pull request merged**
